### ISSUE TITLE
alambda macro

### ISSUE THREAD

**Issue by ghost** [tokenrove/anaphora#2]
In Dug Hoyte's let over lambda, he describes the macro alambda

```
(defmacro alambda (arglist &body body)
  (alexandria:with-unique-names (wrapper-args)
    `(lambda (&rest ,wrapper-args)
       (labels ((anaphora:self (,@arglist) ,@body))
         (funcall anaphora:self ,wrapper-args)))))
```

This macro is rather useful. It can really simplify code that recurses a tree. It would only require exporting the :self symbol from anaphora. I'm not sure if you guys are ok with doing that.

**Comment by tokenrove** [comment]
This seems reasonable.  Of course, it's not uncommon for people to `:use` anaphora, but that's probably something to be discouraged, anyway.

I'm happy to add this myself, but I might not get to it til the weekend.  If you want to submit it as PR before then (with tests, and with our `with-unique-names` instead of alexandria's), feel free.

**Comment by spwhitton** [comment]
> In Dug Hoyte's let over lambda, he describes the macro alambda
> 
> ```
> (defmacro alambda (arglist &body body)
>   (alexandria:with-unique-names (wrapper-args)
>     `(lambda (&rest ,wrapper-args)
>        (labels ((anaphora:self (,@arglist) ,@body))
>          (funcall anaphora:self ,wrapper-args)))))
> ```

The macros in _Let Over Lambda_ and in _On Lisp_ are simpler than this -- I don't believe there is any need for any gensyms.  I've submitted a PR using the version from the books.
