### ISSUE TITLE
Feature request: anaphoric map[car/can] etc, remove-if etc

### ISSUE THREAD

**Issue by fourier** [tokenrove/anaphora#8]
The usage of "it" is really useful in functions which accepts one-argument lambdas.
Even if it is trivial, I guess it is really convenient to type things like
```lisp
(amapcar (+ it 1) '(1 2 3))
(2 3 4)
```
And so on.

**Comment by tokenrove** [comment]
Interesting suggestion!  I would prefer not to put this in `anaphora` and instead suggest the use of general lambda reader macros, for example: https://common-lisp.net/project/bese/docs/arnesi/html/api/function_005FIT.BESE.ARNESI_003A_003ASHARPL-READER.html
I know there are a few variants of this idea out there and perhaps one of them suits you.

I prefer this because it avoids cluttering `anaphora` with an additional macro for every imaginable one-argument lambda function (for example, what about the `:key` arguments on many sequence functions?).  But if you can demonstrate a really compelling case where `amapcar` is definitively better than something like `(mapcar #L(+ it 1) '(1 2 3))`, please reopen this.

Thanks!

**Comment by fourier** [comment]
One counter example for usage of reader macros is what they are providing problems if different packages provide the same reader macro prefix (like this #L ), also doesn't allow sexp-parsing tools (like code coverage in LispWorks) to do their job. 
As for functions, probably the most used better to be implemented. As an example I can refer to "It" in Kotlin programming language where it is used really conveniently: https://kotlinlang.org/docs/reference/lambdas.html#it-implicit-name-of-a-single-parameter

**Comment by tokenrove** [comment]
These are good points, although I don't feel they're that compelling (use [named-readtables](https://common-lisp.net/project/named-readtables/) to manage many readtables, etc).  However I'm just some guy.  If you want to do this, feel free to fork anaphora.
